/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BusinessObject.Cliente;
import TransferObject.ClienteDTO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryam
 */
public class plReporteTablaCliente extends javax.swing.JPanel {
    DefaultTableModel modelo;
    ClienteDTO clienteDTO;
    String personajuridica;
    Cliente cliente;
    /**
     * Creates new form plReporteTipoEmpleado
     */
    public plReporteTablaCliente() {
        initComponents();
        modelo = new DefaultTableModel();
        clienteDTO = new ClienteDTO();
        cliente = new Cliente();
        //cargaDatos();
    }
    
    /*public void cargaDatos() {
        if (plReporteClientes.rbtnJuridica.isSelected()) {
            try {
                modelo = (DefaultTableModel) plReporteTablaCliente.tbReporteClientes.getModel();
                Object[] ob = new Object[8];
                for (ClienteDTO p : cliente.listarPersonaNatural()) {
                    ob[0] = p.getCodCliente();
                    ob[1] = p.getRuc();
                    ob[2] = p.getRazonsocial();
                    ob[3] = p.getNombrecomercial();
                    ob[4] = p.getDireccionfiscal();
                    ob[5] = p.getCelular();
                    ob[6] = p.getDistrito();
                    ob[7] = p.getProvincia();
                    modelo.addRow(ob);
                }
                plReporteTablaCliente.tbReporteClientes.setModel(modelo);
            } catch (Exception ex) {

            }
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReporteClientes = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(137, 176, 212), 2, true)));

        tbReporteClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "RUC", "RAZON SOCIAL", "NOMBRE COMERCIAL", "DIRECCION FISCAL", "CELULAR", "DISTRITO", "PROVINCIA"
            }
        ));
        jScrollPane1.setViewportView(tbReporteClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbReporteClientes;
    // End of variables declaration//GEN-END:variables
}
