/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BusinessObject.Cliente;
import static Presentacion.plVenta.lblFechaVisita;
import static Presentacion.plVenta.txtClienteVisita;
import TransferObject.ClienteDTO;
import TransferObject.EmpleadoDTO;
import TransferObject.RolUsuarioDTO;
import TransferObject.UsuarioDTO;
import Utilities.DisabledItemRenderer;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Francois
 */
public class VentaProductos extends javax.swing.JPanel {
    
    private EmpleadoDTO dtoEmpleado;
    private UsuarioDTO dtoUsuario;
    private RolUsuarioDTO dtoRolUsuario;
    private JFrame jFrame;
    private Cliente oCliente;
    
    ClienteDTO clienteDTO;
    Cliente cliente;
    String ruccliente;
    
    public VentaProductos(EmpleadoDTO dtoEmpleado, UsuarioDTO dtoUsuario, RolUsuarioDTO dtoRolUsuario, JFrame jFrame) {
        this.dtoEmpleado = dtoEmpleado;
        this.dtoUsuario = dtoUsuario;
        this.dtoRolUsuario = dtoRolUsuario;
        this.jFrame = jFrame;
        oCliente = new Cliente();
        initComponents();
        fechaActual();
        //txtClienteVisita.setEnabled(true);
        lblCliente.setEnabled(true);
        btnProcesar.setEnabled(true);
        clienteDTO = new ClienteDTO();
        cliente = new Cliente();
        jBoleta.setVisible(false);
        rellenarClientes();
    }
    
    private void fechaActual() {
        LocalDate fechaActual = LocalDate.now();
        String fechaConvertida = fechaActual.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        lblFecha.setText(fechaConvertida);
    }
    
    public void rellenarClientes(){
        cbClientes.addItem("--Seleccionar--");
        for (ClienteDTO lista : oCliente.listarClientes()) {
            cbClientes.addItem(lista.getRuc());
        }
        cbClientes.setRenderer(new DisabledItemRenderer());
    }

    /**
     * Creates new form VentaProductos
     */
    public VentaProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbClientes = new javax.swing.JComboBox<>();
        btnNuevoCliente = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        chkVenta = new javax.swing.JCheckBox();
        jBoleta = new javax.swing.JPanel();
        jDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSeleccionarProducto = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNumPedido = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBoleta = new javax.swing.JTable();
        btnGenerarBoleta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtImporteTotal = new javax.swing.JTextField();
        btnNuevaBoleta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCerrarBoleta = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 1024));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Visita o Venta"));

        jLabel1.setText("Cliente: ");

        cbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientesActionPerformed(evt);
            }
        });

        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        chkVenta.setText("¿Se realiza venta?");
        chkVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(chkVenta)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcesar)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoCliente)
                    .addComponent(btnProcesar)
                    .addComponent(chkVenta))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 660, 90));

        jBoleta.setBorder(javax.swing.BorderFactory.createTitledBorder("Boleta de Venta"));

        jDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cliente:");
        jDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 163, -1, -1));

        jLabel4.setText("Producto(s):");
        jDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 236, -1, -1));

        btnSeleccionarProducto.setText("Seleccionar");
        btnSeleccionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProductoActionPerformed(evt);
            }
        });
        jDatos.add(btnSeleccionarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 233, -1, -1));

        lblCliente.setText("txtCliente");
        jDatos.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 163, -1, -1));

        jLabel5.setText("Fecha:");
        jDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        lblFecha.setText("txtFecha");
        jDatos.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("R.U.C. XXXXXXXXXXX ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("BOLETA DE VENTA");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("001-");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lblNumPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(lblNumPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        lblNumPedido.getAccessibleContext().setAccessibleName("");

        jDatos.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 226, 109));

        jLabel10.setText("Dirección:");
        jDatos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 195, -1, -1));

        txtDireccionCliente.setText("txtDireccionCliente");
        jDatos.add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 195, -1, -1));

        jLabel11.setText("RUC:");
        jDatos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));
        jDatos.add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        tbBoleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cant.", "Descripción", "P. unit.", "Importe"
            }
        ));
        tbBoleta.setMaximumSize(new java.awt.Dimension(700, 80));
        jScrollPane1.setViewportView(tbBoleta);
        if (tbBoleta.getColumnModel().getColumnCount() > 0) {
            tbBoleta.getColumnModel().getColumn(0).setResizable(false);
            tbBoleta.getColumnModel().getColumn(1).setResizable(false);
        }

        jDatos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 620, 180));

        btnGenerarBoleta.setText("Generar Boleta");
        jDatos.add(btnGenerarBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel2.setText("Total S/");
        jDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));
        jDatos.add(txtImporteTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        btnNuevaBoleta.setText("Nueva Boleta");
        jDatos.add(btnNuevaBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAbastov3.png"))); // NOI18N
        jDatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        javax.swing.GroupLayout jBoletaLayout = new javax.swing.GroupLayout(jBoleta);
        jBoleta.setLayout(jBoletaLayout);
        jBoletaLayout.setHorizontalGroup(
            jBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBoletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
        jBoletaLayout.setVerticalGroup(
            jBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBoletaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 660, 620));

        btnCerrarBoleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnCerrarBoleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarBoleta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarBoletaActionPerformed(evt);
            }
        });
        add(btnCerrarBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        plCliente pCliente = new plCliente();
        pCliente.setSize(750, 560);
        pCliente.setLocation(0, 0);

        //pnlDatos.removeAll();
        //pnlDatos.add(pCliente, BorderLayout.CENTER);
        //pnlDatos.revalidate();
        //pnlDatos.repaint();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void cbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientesActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cbClientesActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        
        if(cbClientes.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Seleccionar cliente");
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnSeleccionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarProductoActionPerformed

    private void btnCerrarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarBoletaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarBoletaActionPerformed

    private void chkVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVentaActionPerformed
        // TODO add your handling code here:
        if(cbClientes.getSelectedIndex() == 0 && chkVenta.isSelected()){
            JOptionPane.showMessageDialog(null, "Seleccionar cliente");
            chkVenta.setSelected(false);
            
        } else if(cbClientes.getSelectedIndex() > 0 && chkVenta.isSelected()) {   
            jBoleta.setVisible(true);
        } else if(cbClientes.getSelectedIndex() > 0 && chkVenta.isSelected()){
            chkVenta.setSelected(false);
            jBoleta.setVisible(false);   
        }
    }//GEN-LAST:event_chkVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarBoleta;
    private javax.swing.JButton btnGenerarBoleta;
    private javax.swing.JButton btnNuevaBoleta;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSeleccionarProducto;
    private javax.swing.JComboBox<String> cbClientes;
    private javax.swing.JCheckBox chkVenta;
    private javax.swing.JPanel jBoleta;
    private javax.swing.JPanel jDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JTable tbBoleta;
    private javax.swing.JLabel txtDireccionCliente;
    private javax.swing.JTextField txtImporteTotal;
    private javax.swing.JLabel txtRUC;
    // End of variables declaration//GEN-END:variables
}
